version: "3.7"

services:
  api:
    build:
      context: ./app/server/
      target: ${TARGET}
    container_name: api
    env_file:
      - ./app/server/.env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - ./app/server/src:/usr/app/server/src
    command: ["npm", "run", "dev"]

    # logging:
    #     driver: "json-file"
    #     options:
    #         max-size: "10m"
    #         max-file: "5"

  db:
    image: postgres:alpine
    container_name: db

    # restart: always
    ports:
      - ${DB_PORT}:5432

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PSOTGRES_USER: ${DB_USER}

  client:
    build:
      context: ./app/client
      target: ${TARGET}
    container_name: client
    env_file:
      - ./app/client/.env
    depends_on:
      - api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - /app/client/node_modules
      - ./app/client/:/usr/app/client/
    command: ["npm", "run", "start"]
    environment:
      CHOKIDAR_USEPOLLING: "true" # seems like this enables hot reloading
    hostname: lutz.com.br
