version: "3.7"

services:
  server:
    build:
      context: ./app/server/
      target: ${DOCKER_TARGET}
    container_name: server
    env_file:
      - ./app/server/.env
    depends_on:
      - db
      - redis
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./app/server/src:/usr/app/server/src
    command: ["npm", "run", "dev"]

##
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis
    env_file:
      - ./.env
    environment:
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/bitnami/redis/data
##
  db:
    image: postgres:alpine
    container_name: db

    # restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PSOTGRES_USER: ${DB_USER}

    volumes:
      - postgres:/var/lib/postresql/data

##
  client:
    build:
      context: ./app/client
      target: ${DOCKER_TARGET}
    container_name: client
    env_file:
      - ./.env
    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - /app/client/node_modules
      - ./app/client/:/usr/app/client/
    command: ["npm", "run", "start"]
    environment:
      CHOKIDAR_USEPOLLING: "true" # seems like this enables hot reloading https://stackoverflow.com/questions/44643045/running-development-server-with-create-react-app-inside-of-a-docker-container
    links:
      - server

# ##
#   webscraper:
#     build:
#       context: ./app/webscraper
#       target: ${DOCKER_TARGET}

#     container_name: webscraper
#     depends_on:
#       - server
#     ports:
#       - ${SERVICE_PORT}:${SERVICE_PORT}
#     volumes:
#       - /app/webscraper/node_modules
#       - ./app/webscraper/:/usr/app/webscraper
#     command: ["npm", "run", "dev"]
#     links:
#       - server

##

volumes:
  postgres:

  redis:
